"""added active status on question

Revision ID: 0de1e6dab413
Revises: 966aa84e17fd
Create Date: 2025-12-23 08:31:51.306151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de1e6dab413'
down_revision: Union[str, None] = '966aa84e17fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE questions SET active = TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'active')
    # ### end Alembic commands ###
