"""progress_fix

Revision ID: 1564e40c6b5a
Revises: 8c9bd3ec1c2e
Create Date: 2025-11-13 23:24:03.703879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1564e40c6b5a'
down_revision: Union[str, None] = '8c9bd3ec1c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
