"""adding user demographic fields

Revision ID: 175a6e389a56
Revises: d4ef2306dc37
Create Date: 2025-11-24 20:51:26.754097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175a6e389a56'
down_revision: Union[str, None] = 'd4ef2306dc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emirati_citizenship', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('age_group', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('place_of_birth', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('current_residence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_residence')
    op.drop_column('users', 'place_of_birth')
    op.drop_column('users', 'age_group')
    op.drop_column('users', 'emirati_citizenship')
    # ### end Alembic commands ###

