"""added token to user

Revision ID: 1adccbf2bab5
Revises: 54cc797c3f1b
Create Date: 2025-11-08 16:18:48.799939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1adccbf2bab5'
down_revision: Union[str, None] = '54cc797c3f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('survey_user_associations_current_question_group_id_fkey'), 'survey_user_associations', type_='foreignkey')
    op.drop_column('survey_user_associations', 'current_question_group_id')
    op.add_column('users', sa.Column('token', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token')
    op.add_column('survey_user_associations', sa.Column('current_question_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('survey_user_associations_current_question_group_id_fkey'), 'survey_user_associations', 'question_groups', ['current_question_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
