"""updated question structure

Revision ID: 54cc797c3f1b
Revises: 91502fdf8ed7
Create Date: 2025-11-08 15:30:38.211387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cc797c3f1b'
down_revision: Union[str, None] = '91502fdf8ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('consent_form', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_number', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('survey_user_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_question_id', sa.Integer(), nullable=True),
    sa.Column('current_question_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_question_group_id'], ['question_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('prompt', sa.Text(), nullable=False))
    op.add_column('questions', sa.Column('response_type', sa.String(length=50), nullable=False))
    op.add_column('questions', sa.Column('question_group_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('survey_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('questions', sa.Column('metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'questions', 'question_groups', ['question_group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'survey_name')
    op.drop_column('questions', 'text')
    op.add_column('survey_logic', sa.Column('survey', sa.Integer(), nullable=False))
    op.add_column('survey_logic', sa.Column('question_group_id', sa.Integer(), nullable=True))
    op.alter_column('survey_logic', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'survey_logic', 'surveys', ['survey'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'survey_logic', 'question_groups', ['question_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('survey_logic', 'survey_name')
    op.drop_column('users', 'survey_name')
    op.drop_column('users', 'last_prompt_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_prompt_sent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('survey_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_logic', sa.Column('survey_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'survey_logic', type_='foreignkey')
    op.drop_constraint(None, 'survey_logic', type_='foreignkey')
    op.alter_column('survey_logic', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('survey_logic', 'question_group_id')
    op.drop_column('survey_logic', 'survey')
    op.add_column('questions', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('survey_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'metadata')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'survey_id')
    op.drop_column('questions', 'question_group_id')
    op.drop_column('questions', 'response_type')
    op.drop_column('questions', 'prompt')
    op.drop_table('survey_user_associations')
    op.drop_table('question_groups')
    op.drop_table('surveys')
    # ### end Alembic commands ###
