"""autogenerate migration

Revision ID: 55cdd38c4447
Revises: bdf0283f3900
Create Date: 2025-12-11 08:08:50.642501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cdd38c4447'
down_revision: Union[str, None] = 'bdf0283f3900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'question_groups', ['name'])
    op.add_column('users', sa.Column('dialect_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dialect_description')
    op.drop_constraint(None, 'question_groups', type_='unique')
    # ### end Alembic commands ###
