"""added required to question

Revision ID: 8c9bd3ec1c2e
Revises: 1adccbf2bab5
Create Date: 2025-11-13 23:06:15.772643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9bd3ec1c2e'
down_revision: Union[str, None] = '1adccbf2bab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('required', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'required')
    # ### end Alembic commands ###
