"""Whatsapp bot integration

Revision ID: 91502fdf8ed7
Revises: 5e9dac8e061c
Create Date: 2025-10-08 14:43:03.700879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91502fdf8ed7'
down_revision: Union[str, None] = '5e9dac8e061c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_logic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_name', sa.String(length=255), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_option_id', sa.String(length=100), nullable=False),
    sa.Column('next_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('prompt_number', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('survey_name', sa.String(length=255), nullable=True))
    op.add_column('responses', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('survey_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_prompt_sent', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'last_prompt_sent')
    op.drop_column('users', 'survey_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('responses', 'metadata')
    op.drop_column('questions', 'survey_name')
    op.drop_column('questions', 'prompt_number')
    op.drop_table('survey_logic')
    # ### end Alembic commands ###
