"""added deletetion token

Revision ID: 966aa84e17fd
Revises: 9c8dcc1e0e6d
Create Date: 2025-12-17 16:31:10.539650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966aa84e17fd'
down_revision: Union[str, None] = '9c8dcc1e0e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_data_token', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'users', ['delete_data_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'delete_data_token')
    # ### end Alembic commands ###
