"""adding real_name_optional_input and phone_number_optional_input to users

Revision ID: 9708e54a1c40
Revises: 175a6e389a56
Create Date: 2025-11-24 21:57:26.866032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9708e54a1c40'
down_revision: Union[str, None] = '175a6e389a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name_optional_input', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone_number_optional_input', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number_optional_input')
    op.drop_column('users', 'real_name_optional_input')
    # ### end Alembic commands ###
