"""added gender and consent_required_2

Revision ID: 9c8dcc1e0e6d
Revises: 55cdd38c4447
Create Date: 2025-12-17 15:38:19.601910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8dcc1e0e6d'
down_revision: Union[str, None] = '55cdd38c4447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('consent_required_2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'consent_required_2')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
