"""questiongroup name nonunique

Revision ID: bdf0283f3900
Revises: f7a8b9c0d1e2
Create Date: 2025-12-07 10:09:52.568547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf0283f3900'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_groups_name_key', 'question_groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('question_groups_name_key', 'question_groups', ['name'])
    # ### end Alembic commands ###
