"""add last_prompt_sent to users

Revision ID: ca42ea4adf03
Revises: e06d3239fdc4
Create Date: 2025-11-21 07:29:27.791896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca42ea4adf03'
down_revision: Union[str, None] = 'e06d3239fdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_prompt_sent', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_prompt_sent')
    # ### end Alembic commands ###
