"""adding survey_name to Questions

Revision ID: d4ef2306dc37
Revises: ee53eebdbfc6
Create Date: 2025-11-21 23:33:45.537008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ef2306dc37'
down_revision: Union[str, None] = 'ee53eebdbfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('survey_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'survey_name')
    # ### end Alembic commands ###
