"""updating consent fields for users

Revision ID: e2f8e3b2ca60
Revises: 9708e54a1c40
Create Date: 2025-11-24 22:15:06.158616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f8e3b2ca60'
down_revision: Union[str, None] = '9708e54a1c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('consent_read_form', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('consent_required', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('consent_optional', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('consent_optional_alternative', sa.Boolean(), nullable=False))
    op.drop_column('users', 'consent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('consent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'consent_optional_alternative')
    op.drop_column('users', 'consent_optional')
    op.drop_column('users', 'consent_required')
    op.drop_column('users', 'consent_read_form')
    # ### end Alembic commands ###
