"""adding task_id to response model

Revision ID: e9376878382c
Revises: 0de1e6dab413
Create Date: 2026-02-12 10:06:23.394037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9376878382c'
down_revision: Union[str, None] = '0de1e6dab413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('audino_task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'audino_task_id')
    # ### end Alembic commands ###
