"""nullable token field for users

Revision ID: ee53eebdbfc6
Revises: ca42ea4adf03
Create Date: 2025-11-21 22:01:47.077073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee53eebdbfc6'
down_revision: Union[str, None] = 'ca42ea4adf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('users_token_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_token_key', 'users', ['token'])
    op.alter_column('users', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
